name: Test apt-cache Action

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test-with-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test apt-cache with update
        uses: ./
        with:
          packages: 'ansible'
          run_update: true
          
      - name: Verify installation
        run: |
          ansible --version

  test-without-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Test apt-cache without update
        uses: ./
        with:
          packages: ansible fail2ban
          # run_update defaults to false
      
      - name: Verify installation
        run: |
          ansible --version
